SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

INITIAL_SNAKE_SEGMENTS_NUM = 3
FORWARD_MOVE_DISTANCE = 20
SNAKE_SQUARE_SEGMENT_SIZE = 20

UP = 90
DOWN = 270
LEFT = 180
RIGHT = 0

FOOD_COLLIDING_DISTANCE = 15
WALL_COLLIDING_DISTANCE = 15

SCOREBOARD_CENTER_ALIGN = "center"
SCOREBOARD_FONT = ("Times New Roman", 14, "bold")
